---
- hosts: [sas_servers]
  become: yes
  become_user: root
  vars_files:
    - /sas/install/ansible/vars.yaml
    
  tasks:
    - name: Ensure "sas" group exists
      group:
        name: sas
        gid: 1003
        state: present

    - name: Ensure "sasinst" user exists, set password
      user:
        name: sasinst
        uid: 501
        password: "{{ AdminPassword | password_hash('sha512') }}"
        group: sas

    - name: Ensure "sas" user exists, set password
      user:
        name: sas
        uid: 503
        password: "{{ AdminPassword | password_hash('sha512') }}"
        group: sas

    - name: Ensure "sasdemo" user exists, set password
      user:
        name: sasdemo
        uid: 504
        password: "{{ AdminPassword | password_hash('sha512') }}"
        group: sas

    - name: Ensure "sassrv" user exists, set password
      user:
        name: sassrv
        uid: 505
        password: "{{ AdminPassword | password_hash('sha512) }}"
        group: sas

    - name: Ensure "sastrust" user exists, set password
      user:
        name: sastr
        uid: 506
        password: "{{ AdminPassword | password_hash('sha512') }}"
        group: sas

    - name: Ensure "sasadm" user exists, set password
      user:
        name: sasadm
        uid: 508
        password: "{{ AdminPassword | password_hash('sha512') }}"
        group: sas

    - name: Ensure "sasevs" user exists, set password
      user:
        name: sasevs
        uid: 508
        password: "{{ AdminPassword | password_hash('sha512') }}"
        group: sas

    - name: Ensure "webanon" user exists, set password
      user:
        name: webanon
        uid: 509
        password: "{{ AdminPassword | password_hash('sha512') }}"
        group: sas
